# Generated by Django 5.2.8 on 2026-01-27 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0005_alter_workspace_id_alter_workspacemembership_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='workspace',
            field=models.ForeignKey(blank=False, null=False, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='task_manager.workspace'),
        ),
    ]
