# Generated by Django 5.2.8 on 2026-01-27 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0005_backfill_workspace'),
        ('task_manager', '0006_alter_task_workspace'),
    ]

    operations = [
    ]
