# Generated by Django 5.2.8 on 2026-01-28 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0008_add_visit_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='position',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='visit_count',
        ),
        migrations.AddField(
            model_name='worker',
            name='role',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
