# Generated by Django 5.2.8 on 2026-01-28 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0009_remove_worker_position_remove_worker_visit_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='visit_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
